version: "3.2"
services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - advance-todo
    env_file: 
      - local.env

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASS}
    environment:
      REDIS_REPLICATION_MODE: ${REDIS_REPLICATION_MODE}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis-data:/var/lib/redis
      - redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - advance-todo
    env_file: 
      - local.env

networks:
  advance-todo:
    driver: bridge

volumes:
  database-data:
  redis-data:
  redis.conf:
